baseurl = "https://jamaalroach.com/"
languageCode = "en"
title = "JamaalRoach"
copyright = "2018 JROACH"
paginate = 3

googleAnalytics = "     "
disqusShortname = "jamaalroach-com"

theme = "minimage"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  description = "Updating Priors"
  author = "Jamaal Roach"
  logo = '/img/me.jpg'

[taxonomies]
  category = "categories"
  tag = "tags"

[twitter]
  card = "summary_large_image"
  site = "@twittername"
  creator = "@twitternameofcreator"
  title = "Special Title for the Card"
  description = "Special Description for the card max. 200 characters"
  image = "https://example.com/great-picture.jpg"
  
[[menu.global]]
    name = "Contact"
    url = "/page/contact/"

[[menu.global]]
    name = "About"
    url = "/page/about/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
