baseurl = "https://jamaalroach.com"
languageCode = "en"
title = "Jamaal Roach"
copyright = "2018 JROACH"
paginate = 3

googleAnalytics = "     "
disqusShortname = "jamaalroach-com"

theme = "minimage"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  description = "What the R....?!?"
  author = "Jamaal Roach"
  logo = '/img/me.jpg'

[taxonomies]
  category = "categories"
  tag = "tags"


[[menu.global]]
    name = "Contact"
    url = "/page/contact/"

[[menu.global]]
    name = "About"
    url = "/page/about/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
